import Head from "next/head";
import PageableWrapper from "../components/PageableWrapper";

export default function Home() {
  return (
    <>
      <Head>
        <title>Supreme Korea Celebration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageableWrapper />
    </>
  );
}
